//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCricket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Team
    {
        public int Id { get; set; }
        public Nullable<int> Player_Id { get; set; }
        public Nullable<int> Team_Id { get; set; }
    
        public virtual tbl_Player tbl_Player { get; set; }
        public virtual tbl_Team tbl_Team { get; set; }
    }
}
