//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCricket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Type
    {
        public int Type_Id { get; set; }
        public string Type_Name { get; set; }
    
        public virtual tbl_Type tbl_Type1 { get; set; }
        public virtual tbl_Type tbl_Type2 { get; set; }
    }
}
